import i18n from 'i18next';
import { initReactI18next } from 'react-i18next';

export const languages = ['pt-BR', 'en', 'es', 'pt-PT'] as const;
export type Language = (typeof languages)[number];

const translations: Record<Language, Record<string, string>> = {
  'pt-BR': {
    'meta.title': 'João Vitor | Desenvolvedor Full Stack', 'meta.description': 'Crio sites, sistemas e automações que vendem, organizam e escalam.',
    'nav.services': 'Serviços', 'nav.projects': 'Projetos', 'nav.method': 'Método', 'nav.contact': 'Contato', 'nav.cta': 'Falar agora',
    'hero.title': 'Transformo operação no improviso em sistema que escala.',
    'hero.subtitle': 'Planilha, caderno e WhatsApp não seguram crescimento. Eu construo o site, sistema ou automação que organiza seu processo, funcionando em dias, não meses.',
    'common.whatsapp': 'Falar no WhatsApp', 'hero.projects': 'Ver Projetos',
    'stats.projects': 'Projetos entregues com sucesso', 'stats.volume': 'Movimentados em sistemas', 'stats.years': 'Anos transformando processos',
    'services.title': 'Não vendo projeto. Vendo resultado.',
    'services.site.title': 'Sites que vendem', 'services.site.body': 'Landing pages, portfólios e lojas que convertem visitante em cliente. Visual premium, velocidade real.', 'services.site.cta': 'Quero um site que venda',
    'services.systems.title': 'Sistemas internos', 'services.systems.body': 'Dashboards, ERPs, CRMs e painéis que substituem planilha e WhatsApp. Operação que escala.', 'services.systems.cta': 'Quero organizar minha operação',
    'services.automation.title': 'Automação & IA', 'services.automation.body': 'Processos repetitivos viram fluxos automáticos e IA integrada onde faz sentido. Já fiz bots, scraping e consultas em Python, mas meu foco é produto. Tempo de volta pra você.', 'services.automation.cta': 'Quero automatizar processos',
    'pain.title': 'Meu trabalho entra quando o improviso para de funcionar.', 'pain.growth.title': 'Negócio cresce, operação trava', 'pain.growth.body': 'Clientes chegam, tarefas aumentam e a equipe começa a perder tempo com controle manual retrabalho e falta de visibilidade.',
    'pain.whatsapp.title': 'Tudo depende do WhatsApp', 'pain.whatsapp.body': 'Pedidos, pagamentos, aprovações e informações importantes ficam espalhados em conversas difíceis de controlar.',
    'pain.idea.title': 'Ideia boa sem execução', 'pain.idea.body': 'Você sabe o que precisa construir, mas precisa de alguém que entenda o problema, organize o escopo e entregue funcionando.',
    'projects.title': 'Projetos que deixaram marca.', 'projects.vet.category': 'SAAS · VETERINÁRIA', 'projects.vet.body': 'Sistema de controlo anestésico para clínicas veterinárias. Substituiu fichas de papel.',
    'projects.delivery.category': 'PLATAFORMA · DELIVERY', 'projects.delivery.body': 'Plataforma de gestão para serviços de entrega. Do pedido ao motoboy em tempo real.', 'projects.foreign': 'Cliente fora do Brasil',
    'projects.glow.category': 'APP · BELEZA', 'projects.glow.body': 'App de agendamento para salões de beleza com cliente internacional. Agendamentos que iam por DM, agora têm portal próprio.',
    'projects.home.category': 'MARKETPLACE · IMÓVEIS', 'projects.home.body': 'Marketplace de imóveis com filtros geográficos e tour virtual. Conecta corretor e comprador.',
    'projects.moto.category': 'SAAS · ALUGUEL DE MOTOS', 'projects.moto.body': 'Sistema completo de gestão de reservas e frota de motos. Do checkout ao controle operacional em tempo real.',
    'projects.eboy.body': 'Plataforma de pedidos e entregas que conecta clientes, estabelecimentos e entregadores, simplificando a operação e acompanhando cada pedido em tempo real.',
    'projects.car.category': 'PLATAFORMA + APP · MÍDIA OOH', 'projects.car.body': 'Plataforma e aplicativo de mídia OOH móvel que conecta marcas a motoristas, transformando veículos em canais de publicidade e criando novas oportunidades de renda.',
    'testimonials.title': 'Quem já trabalhou comigo.', 'testimonials.readMore': 'Ler mais', 'testimonials.readLess': 'Ler menos',
    'cta.title': 'Vamos tirar sua ideia do papel?', 'cta.body': 'Uma conversa rápida no WhatsApp já define o que precisa ser feito. Sem compromisso, sem rodeio.',
    'method.title': 'Simples|Direto|Entregue', 'method.step': 'Passo {{number}}', 'method.discover.title': 'Descubro o gargalo real', 'method.discover.body': 'Não começo a codar antes de entender o problema. Uma conversa rápida já define o que vai mudar o negócio de verdade.',
    'method.build.title': 'Construo rápido', 'method.build.body': 'Sem burocracia. MVP funcionando em dias, não meses. Você vê e testa real, não slide de apresentação.',
    'method.adjust.title': 'Ajusto com dados reais', 'method.adjust.body': 'Depois do lançamento o trabalho continua. Analiso o que funciona e ajusto. Entrego resultado, não código.',
    'contact.title': 'Tem uma ideia para tirar do papel?', 'contact.body': 'Me chame no WhatsApp e eu te ajudo a transformar sua ideia ou processo travado em uma solução simples, funcional e pronta para uso.',
    'contact.ready': 'Pronto para começar?', 'contact.cardBody': 'Mande uma mensagem direta no WhatsApp para uma resposta mais rápida e alinhamento do seu projeto.', 'contact.start': 'Iniciar Conversa',
    'common.backToTop': 'Voltar ao topo', 'footer.copyright': '© 2026', 'aria.language': 'Idioma',
    'testimonials.0.project': 'App de anestesiologia veterinária', 'testimonials.0.text': 'Excelente programador! Entregou antes do prazo final, muito comprometido e tem ótima comunicação. Continuarei trabalhando com ele no meu app futuramente, e certamente recomendaria para colegas!',
    'testimonials.1.project': 'Sistema de gestão de inscrições', 'testimonials.1.text': 'Profissional muito prestativo e competente.', 'testimonials.2.project': 'Site e app para cadastro e pesquisa', 'testimonials.2.text': 'Super prestativo',
    'testimonials.3.project': 'App mobile com WebSocket', 'testimonials.3.text': 'Recomendo. Prestativo e tudo de acordo com o combinado', 'testimonials.4.project': 'Portal de anúncios imobiliários', 'testimonials.4.text': 'Excelente profissional!!! conhecimento e domínio incrível. Já trabalhei com diversos profissionais, mas o programador João se destaca. Pontual, dedicado, compreende o projeto, paciente e executa com agilidade e profissionalismo. Sem sombra de dúvida ganhou um cliente, espero seguir sempre com a parceria, não trocaria este profissional por nenhum da plataforma 99freelas.',
  },
  en: {
    'meta.title': 'João Vitor | Full Stack Developer', 'meta.description': 'I build websites, systems, and automations that sell, organize, and scale.',
    'nav.services': 'Services', 'nav.projects': 'Projects', 'nav.method': 'Approach', 'nav.contact': 'Contact', 'nav.cta': 'Let’s talk',
    'hero.title': 'I turn improvised operations into systems that scale.', 'hero.subtitle': 'Spreadsheets, notebooks, and WhatsApp cannot sustain growth. I build websites, systems, and automations that organize your workflow in days rather than months.', 'common.whatsapp': 'Chat on WhatsApp', 'hero.projects': 'View projects',
    'stats.projects': 'Projects successfully delivered', 'stats.volume': 'Processed through systems', 'stats.years': 'Years transforming processes',
    'services.title': 'I don’t sell projects. I deliver results.', 'services.site.title': 'Websites that sell', 'services.site.body': 'Landing pages, portfolios, and stores that turn visitors into customers. Premium design, real speed.', 'services.site.cta': 'I want a website that sells',
    'services.systems.title': 'Internal systems', 'services.systems.body': 'Dashboards, ERPs, CRMs, and tools that replace spreadsheets and WhatsApp. Operations built to scale.', 'services.systems.cta': 'I want to organize my operations',
    'services.automation.title': 'Automation & AI', 'services.automation.body': 'Repetitive tasks become automated workflows, with AI where it makes sense. I’ve built bots, scrapers, and Python integrations, but my focus is product. Get your time back.', 'services.automation.cta': 'I want to automate processes',
    'pain.title': 'I step in when improvisation stops working.', 'pain.growth.title': 'The business grows, operations stall', 'pain.growth.body': 'Customers arrive, tasks pile up, and the team wastes time on manual tracking, rework, and lack of visibility.', 'pain.whatsapp.title': 'Everything depends on WhatsApp', 'pain.whatsapp.body': 'Orders, payments, approvals, and important information are scattered across hard-to-manage conversations.', 'pain.idea.title': 'A good idea with no execution', 'pain.idea.body': 'You know what you need to build, but need someone who understands the problem, defines the scope, and delivers a working solution.',
    'projects.title': 'Projects that made a mark.', 'projects.vet.category': 'SAAS · VETERINARY', 'projects.vet.body': 'Anaesthesia monitoring system for veterinary clinics. Replaced paper records.', 'projects.delivery.category': 'PLATFORM · DELIVERY', 'projects.delivery.body': 'Delivery service management platform. From order to courier, in real time.', 'projects.foreign': 'International client', 'projects.glow.category': 'APP · BEAUTY', 'projects.glow.body': 'Booking app for beauty salons serving international clients. Appointments once managed through DMs now have their own portal.', 'projects.home.category': 'MARKETPLACE · REAL ESTATE', 'projects.home.body': 'Real estate marketplace with location filters and virtual tours. Connecting agents and buyers.', 'projects.moto.category': 'SAAS · MOTORBIKE RENTALS', 'projects.moto.body': 'Complete booking and motorbike fleet management system. From checkout to real-time operations.', 'projects.eboy.body': 'Ordering and delivery platform connecting customers, businesses, and couriers, simplifying operations and tracking every order in real time.', 'projects.car.category': 'PLATFORM + APP · OOH MEDIA', 'projects.car.body': 'Mobile out-of-home advertising platform connecting brands and drivers, turning vehicles into ad channels and creating new income opportunities.',
    'testimonials.title': 'What clients say.', 'testimonials.readMore': 'Read more', 'testimonials.readLess': 'Read less', 'cta.title': 'Ready to bring your idea to life?', 'cta.body': 'A quick WhatsApp chat is enough to define what needs to be done. No pressure, no runaround.', 'method.title': 'Simple|Direct|Delivered', 'method.step': 'Step {{number}}', 'method.discover.title': 'I find the real bottleneck', 'method.discover.body': 'I don’t start coding before understanding the problem. A quick conversation can define what will truly move your business forward.', 'method.build.title': 'I build fast', 'method.build.body': 'No bureaucracy. An MVP working in days, not months. You see and test something real, not a presentation slide.', 'method.adjust.title': 'I refine with real data', 'method.adjust.body': 'Work continues after launch. I analyze what works and make adjustments. I deliver results, not code.',
    'contact.title': 'Have an idea you want to bring to life?', 'contact.body': 'Message me on WhatsApp and I’ll help turn your idea or stalled process into a simple, functional solution that’s ready to use.', 'contact.ready': 'Ready to get started?', 'contact.cardBody': 'Send a direct WhatsApp message for a faster reply and to align on your project.', 'contact.start': 'Start a conversation', 'common.backToTop': 'Back to top', 'footer.copyright': '© 2026', 'aria.language': 'Language',
    'testimonials.0.project': 'Veterinary anaesthesia app', 'testimonials.0.text': 'Excellent developer! Delivered ahead of schedule, highly committed, and a great communicator. I’ll keep working with him on my app and would definitely recommend him to colleagues!', 'testimonials.1.project': 'Registration management system', 'testimonials.1.text': 'Very helpful and competent professional.', 'testimonials.2.project': 'Registration and search website and app', 'testimonials.2.text': 'Extremely helpful.', 'testimonials.3.project': 'Mobile app with WebSocket', 'testimonials.3.text': 'Recommended. Helpful, and everything was delivered as agreed.', 'testimonials.4.project': 'Real estate listings portal', 'testimonials.4.text': 'An outstanding professional with incredible knowledge and expertise. I’ve worked with many people, but João stands out. Punctual, dedicated, patient, quick, and professional. He has definitely gained a client, and I hope we keep working together.',
  },
  es: {
    'meta.title': 'João Vitor | Desarrollador Full Stack', 'meta.description': 'Creo sitios, sistemas y automatizaciones que venden, organizan y ayudan a crecer.',
    'nav.services': 'Servicios', 'nav.projects': 'Proyectos', 'nav.method': 'Método', 'nav.contact': 'Contacto', 'nav.cta': 'Hablemos',
    'hero.title': 'Transformo operaciones improvisadas en sistemas que crecen.', 'hero.subtitle': 'Las hojas de cálculo, las libretas y WhatsApp no sostienen el crecimiento. Creo sitios, sistemas y automatizaciones que organizan tu proceso en días, no meses.', 'common.whatsapp': 'Hablar por WhatsApp', 'hero.projects': 'Ver proyectos',
    'stats.projects': 'Proyectos entregados con éxito', 'stats.volume': 'Gestionados en sistemas', 'stats.years': 'Años transformando procesos', 'services.title': 'No vendo proyectos. Entrego resultados.', 'services.site.title': 'Sitios que venden', 'services.site.body': 'Landing pages, portafolios y tiendas que convierten visitas en clientes. Diseño premium y velocidad real.', 'services.site.cta': 'Quiero un sitio que venda',
    'services.systems.title': 'Sistemas internos', 'services.systems.body': 'Paneles, ERPs, CRMs y herramientas que reemplazan hojas de cálculo y WhatsApp. Operaciones listas para crecer.', 'services.systems.cta': 'Quiero organizar mi operación', 'services.automation.title': 'Automatización e IA', 'services.automation.body': 'Las tareas repetitivas se convierten en flujos automáticos, con IA cuando tiene sentido. He creado bots, scrapers e integraciones con Python, pero mi enfoque es el producto. Recupera tu tiempo.', 'services.automation.cta': 'Quiero automatizar procesos',
    'pain.title': 'Entro en acción cuando la improvisación deja de funcionar.', 'pain.growth.title': 'El negocio crece, la operación se atasca', 'pain.growth.body': 'Llegan clientes, aumentan las tareas y el equipo pierde tiempo con controles manuales, retrabajo y falta de visibilidad.', 'pain.whatsapp.title': 'Todo depende de WhatsApp', 'pain.whatsapp.body': 'Pedidos, pagos, aprobaciones e información importante quedan dispersos en conversaciones difíciles de controlar.', 'pain.idea.title': 'Una buena idea sin ejecución', 'pain.idea.body': 'Sabes qué necesitas construir, pero necesitas a alguien que entienda el problema, defina el alcance y entregue algo funcional.',
    'projects.title': 'Proyectos que dejaron huella.', 'projects.vet.category': 'SAAS · VETERINARIA', 'projects.vet.body': 'Sistema de monitorización anestésica para clínicas veterinarias. Sustituyó las fichas de papel.', 'projects.delivery.category': 'PLATAFORMA · DELIVERY', 'projects.delivery.body': 'Plataforma de gestión de entregas. Del pedido al repartidor en tiempo real.', 'projects.foreign': 'Cliente internacional', 'projects.glow.category': 'APP · BELLEZA', 'projects.glow.body': 'App de reservas para salones de belleza con clientela internacional. Las citas que se gestionaban por mensajes ahora tienen su propio portal.', 'projects.home.category': 'MARKETPLACE · INMOBILIARIO', 'projects.home.body': 'Marketplace inmobiliario con filtros geográficos y recorridos virtuales. Conecta agentes y compradores.', 'projects.moto.category': 'SAAS · ALQUILER DE MOTOS', 'projects.moto.body': 'Sistema completo de reservas y gestión de flota de motos. Desde el pago hasta la operación en tiempo real.', 'projects.eboy.body': 'Plataforma de pedidos y entregas que conecta clientes, comercios y repartidores, simplifica la operación y permite seguir cada pedido en tiempo real.', 'projects.car.category': 'PLATAFORMA + APP · PUBLICIDAD EXTERIOR', 'projects.car.body': 'Plataforma móvil de publicidad exterior que conecta marcas y conductores, convierte vehículos en canales publicitarios y crea nuevas oportunidades de ingresos.',
    'testimonials.title': 'Quienes ya trabajaron conmigo.', 'testimonials.readMore': 'Leer más', 'testimonials.readLess': 'Leer menos', 'cta.title': '¿Le damos vida a tu idea?', 'cta.body': 'Una charla rápida por WhatsApp basta para definir lo que hay que hacer. Sin compromiso y sin rodeos.', 'method.title': 'Simple|Directo|Entregado', 'method.step': 'Paso {{number}}', 'method.discover.title': 'Encuentro el verdadero cuello de botella', 'method.discover.body': 'No empiezo a programar antes de entender el problema. Una charla rápida define qué hará avanzar realmente tu negocio.', 'method.build.title': 'Construyo rápido', 'method.build.body': 'Sin burocracia. Un MVP funcionando en días, no meses. Ves y pruebas algo real, no una presentación.', 'method.adjust.title': 'Ajusto con datos reales', 'method.adjust.body': 'El trabajo continúa después del lanzamiento. Analizo lo que funciona y lo ajusto. Entrego resultados, no código.',
    'contact.title': '¿Tienes una idea que quieres hacer realidad?', 'contact.body': 'Escríbeme por WhatsApp y te ayudaré a convertir tu idea o proceso estancado en una solución sencilla, funcional y lista para usar.', 'contact.ready': '¿Listo para empezar?', 'contact.cardBody': 'Envíame un mensaje directo por WhatsApp para recibir una respuesta más rápida y definir tu proyecto.', 'contact.start': 'Iniciar conversación', 'common.backToTop': 'Volver arriba', 'footer.copyright': '© 2026', 'aria.language': 'Idioma',
    'testimonials.0.project': 'App de anestesiología veterinaria', 'testimonials.0.text': '¡Excelente programador! Entregó antes de la fecha, muy comprometido y con una comunicación estupenda. Seguiré trabajando con él en mi app y sin duda lo recomendaría a mis colegas.', 'testimonials.1.project': 'Sistema de gestión de inscripciones', 'testimonials.1.text': 'Profesional muy atento y competente.', 'testimonials.2.project': 'Sitio y app de registro y búsqueda', 'testimonials.2.text': 'Muy atento.', 'testimonials.3.project': 'App móvil con WebSocket', 'testimonials.3.text': 'Lo recomiendo. Atento y todo según lo acordado.', 'testimonials.4.project': 'Portal de anuncios inmobiliarios', 'testimonials.4.text': '¡Excelente profesional, con conocimientos y dominio increíbles! He trabajado con muchos profesionales, pero João destaca por ser puntual, dedicado, paciente y profesional. Sin duda ha ganado un cliente y espero que sigamos colaborando.',
  },
  'pt-PT': {
    'meta.title': 'João Vitor | Programador Full Stack', 'meta.description': 'Desenvolvo sites, sistemas e automatizações que vendem, organizam e fazem crescer.',
    'nav.services': 'Serviços', 'nav.projects': 'Projetos', 'nav.method': 'Método', 'nav.contact': 'Contacto', 'nav.cta': 'Falar agora',
    'hero.title': 'Transformo operações improvisadas em sistemas que crescem.', 'hero.subtitle': 'Folhas de cálculo, cadernos e WhatsApp não acompanham o crescimento. Desenvolvo sites, sistemas e automatizações que organizam o seu processo em dias, não em meses.', 'common.whatsapp': 'Falar pelo WhatsApp', 'hero.projects': 'Ver projetos', 'stats.projects': 'Projetos entregues com sucesso', 'stats.volume': 'Movimentados em sistemas', 'stats.years': 'Anos a transformar processos',
    'services.title': 'Não vendo projetos. Entrego resultados.', 'services.site.title': 'Sites que vendem', 'services.site.body': 'Landing pages, portefólios e lojas que transformam visitantes em clientes. Visual premium e rapidez real.', 'services.site.cta': 'Quero um site que venda', 'services.systems.title': 'Sistemas internos', 'services.systems.body': 'Dashboards, ERPs, CRMs e ferramentas que substituem folhas de cálculo e WhatsApp. Operações preparadas para crescer.', 'services.systems.cta': 'Quero organizar a minha operação', 'services.automation.title': 'Automatização e IA', 'services.automation.body': 'As tarefas repetitivas passam a fluxos automáticos, com IA quando faz sentido. Já desenvolvi bots, scraping e integrações em Python, mas o meu foco é o produto. Recupere o seu tempo.', 'services.automation.cta': 'Quero automatizar processos',
    'pain.title': 'Entro em ação quando a improvisação deixa de funcionar.', 'pain.growth.title': 'O negócio cresce, a operação bloqueia', 'pain.growth.body': 'Chegam clientes, aumentam as tarefas e a equipa perde tempo com controlo manual, retrabalho e falta de visibilidade.', 'pain.whatsapp.title': 'Tudo depende do WhatsApp', 'pain.whatsapp.body': 'Pedidos, pagamentos, aprovações e informações importantes ficam dispersos em conversas difíceis de gerir.', 'pain.idea.title': 'Uma boa ideia sem execução', 'pain.idea.body': 'Sabe o que precisa de construir, mas precisa de alguém que compreenda o problema, defina o âmbito e entregue algo funcional.',
    'projects.title': 'Projetos que deixaram marca.', 'projects.vet.category': 'SAAS · VETERINÁRIA', 'projects.vet.body': 'Sistema de monitorização anestésica para clínicas veterinárias. Substituiu os registos em papel.', 'projects.delivery.category': 'PLATAFORMA · DELIVERY', 'projects.delivery.body': 'Plataforma de gestão de entregas. Do pedido ao estafeta, em tempo real.', 'projects.foreign': 'Cliente internacional', 'projects.glow.category': 'APP · BELEZA', 'projects.glow.body': 'App de marcações para salões de beleza com clientes internacionais. As marcações feitas por mensagem têm agora um portal próprio.', 'projects.home.category': 'MARKETPLACE · IMOBILIÁRIO', 'projects.home.body': 'Marketplace imobiliário com filtros geográficos e visitas virtuais. Liga agentes e compradores.', 'projects.moto.category': 'SAAS · ALUGUER DE MOTOS', 'projects.moto.body': 'Sistema completo de reservas e gestão de frota de motos. Do pagamento à operação em tempo real.', 'projects.eboy.body': 'Plataforma de pedidos e entregas que liga clientes, estabelecimentos e estafetas, simplifica a operação e acompanha cada pedido em tempo real.', 'projects.car.category': 'PLATAFORMA + APP · PUBLICIDADE EXTERIOR', 'projects.car.body': 'Plataforma móvel de publicidade exterior que liga marcas e condutores, transforma veículos em canais publicitários e cria novas oportunidades de rendimento.',
    'testimonials.title': 'Quem já trabalhou comigo.', 'testimonials.readMore': 'Ler mais', 'testimonials.readLess': 'Ler menos', 'cta.title': 'Vamos tirar a sua ideia do papel?', 'cta.body': 'Uma conversa rápida pelo WhatsApp chega para definir o que é preciso fazer. Sem compromisso e sem rodeios.', 'method.title': 'Simples|Direto|Entregue', 'method.step': 'Passo {{number}}', 'method.discover.title': 'Descubro o verdadeiro bloqueio', 'method.discover.body': 'Não começo a programar antes de compreender o problema. Uma conversa rápida define o que vai realmente fazer o negócio avançar.', 'method.build.title': 'Construo rapidamente', 'method.build.body': 'Sem burocracia. MVP funcional em dias, não em meses. Vê e testa algo real, não um slide de apresentação.', 'method.adjust.title': 'Ajusto com dados reais', 'method.adjust.body': 'O trabalho continua depois do lançamento. Analiso o que funciona e ajusto. Entrego resultados, não código.',
    'contact.title': 'Tem uma ideia para tirar do papel?', 'contact.body': 'Contacte-me pelo WhatsApp e ajudo a transformar a sua ideia ou processo bloqueado numa solução simples, funcional e pronta a utilizar.', 'contact.ready': 'Pronto para começar?', 'contact.cardBody': 'Envie uma mensagem direta pelo WhatsApp para obter uma resposta mais rápida e alinharmos o seu projeto.', 'contact.start': 'Iniciar conversa', 'common.backToTop': 'Voltar ao topo', 'footer.copyright': '© 2026', 'aria.language': 'Idioma',
    'testimonials.0.project': 'App de anestesiologia veterinária', 'testimonials.0.text': 'Excelente programador! Entregou antes do prazo, muito empenhado e com uma ótima comunicação. Continuarei a trabalhar com ele na minha app e recomendá-lo-ia certamente aos meus colegas.', 'testimonials.1.project': 'Sistema de gestão de inscrições', 'testimonials.1.text': 'Profissional muito prestável e competente.', 'testimonials.2.project': 'Site e app de registo e pesquisa', 'testimonials.2.text': 'Muito prestável.', 'testimonials.3.project': 'App móvel com WebSocket', 'testimonials.3.text': 'Recomendo. Prestável e tudo conforme combinado.', 'testimonials.4.project': 'Portal de anúncios imobiliários', 'testimonials.4.text': 'Excelente profissional, com conhecimentos e domínio incríveis! Já trabalhei com vários profissionais, mas o João destaca-se. Pontual, dedicado, paciente e profissional. Sem dúvida ganhou um cliente e espero que continuemos a trabalhar juntos.',
  },
};

void i18n.use(initReactI18next).init({
  resources: Object.fromEntries(languages.map((language) => [language, { translation: translations[language] }])),
  lng: 'pt-BR',
  fallbackLng: 'pt-BR',
  interpolation: { escapeValue: false },
  initAsync: false,
});

export function translate(language: Language, key: string, values?: Record<string, string>) {
  return i18n.t(key, { lng: language, ...values });
}

export { i18n };

export function getSavedLanguage(): Language {
  const saved = localStorage.getItem('language');
  return languages.includes(saved as Language) ? saved as Language : 'pt-BR';
}
